### ISSUE TITLE
Firebolt does not seem to work in 46

### ISSUE THREAD

**Issue by dragonsahead** [firebolt-db/metabase-firebolt-driver#37]
Just leaving this here https://github.com/metabase/metabase/issues/29995

**Comment by aymeric-dispa** [comment]
Hi @paoliniluis,

I am the one who opened the issue that you just shared, as I am responsible for the development of the Firebolt driver. I tested the latest driver (v1.0.12) with Metabase versions v0.45.3.1 and v0.46.1, and it is only failing with the latter. This is why I opened the issue, as it seems to be related to a recent change in Metabase. Is there any change needed in the driver in order to support the latest version of Metabase ?

**Comment by dragonsahead** [comment]
thanks! I didn't check that before posting here. We're reviewing what's going on internally

**Comment by aymeric-dispa** [comment]
No problem, thanks 👍 !
